baseURL =  'https://localhost:1313/'
languageCode = 'en-us'
title = 'Sandra Gesing'
theme = "papermod"

[params]
  homeInfoParams = false
  showPostsOnHomePage = false
  showToc = true 

[markup.goldmark.renderer]
    unsafe = true

tags = ["journal", "conference", "white-paper", "book", "edited",  "special", "misc"]

[menu]

  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    pageRef = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Awards"
    pageRef = "/awards/"
    weight = 3

  [[menu.main]]
    name = "Publications"
    identifier = "publications"
    pageRef = "/publications/"
    weight = 4

  
  [[menu.main]]
    name = "Lectures and Talks"
    pageRef = "/lectures-and-talks/"
    weight = 5

  [[menu.main]]
    name = "Professional Services"
    pageRef = "/professional-services/"
    weight = 6

  [[menu.main]]
    name = "Bio"
    pageRef = "/bio/"
    weight = 7

  [[menu.main]]
    name = "In the Press"
    pageRef = "/in-the-press/"
    weight = 8

  [[menu.main]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 9

  [[menu.main]]
    name = "Journal"
    pageRef = "/publications/journals"
    parent = "publications"
    weight = 10

  [[menu.main]]
    name = "Conference"
    pageRef = "/publications/peer-reviewed-conferences"
    parent = "publications"
    weight = 20

  [[menu.main]]
    name = "White Paper"
    pageRef = "/publications/white-papers"
    parent = "publications"
    weight = 30

  [[menu.main]]
    name = "Book"
    pageRef = "/publications/book-chapters"
    parent = "publications"
    weight = 40

  [[menu.main]]
    name = "Edited"
    pageRef = "/publications/edited-proceedings"
    parent = "publications"
    weight = 50

  [[menu.main]]
    name = "Special"
    pageRef = "/publications/special-issues"
    parent = "publications"
    weight = 60

  [[menu.main]]
    name = "Misc"
    pageRef = "/publications/misc"
    parent = "publications"
    weight = 70